//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaColegioEF.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EscuelaDB : DbContext
    {
        public EscuelaDB()
            : base("name=EscuelaDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumnoes { get; set; }
        public virtual DbSet<Alumno_Materia> Alumno_Materia { get; set; }
        public virtual DbSet<AlumnoAsistencia> AlumnoAsistencias { get; set; }
        public virtual DbSet<Calificacion> Calificacions { get; set; }
        public virtual DbSet<Escuela> Escuelas { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<NotaPorPeriodo> NotaPorPeriodoes { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<ProfAsistencia> ProfAsistencias { get; set; }
        public virtual DbSet<Profesor> Profesors { get; set; }
        public virtual DbSet<Profesor_Materia> Profesor_Materia { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
