//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaColegioEF.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int idRoles { get; set; }
        public string permiso { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
